apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: default
type: Opaque
stringData:
  superUserPassword: k8spostgresChallengeSU
  replicationUserPassword: k8spostgresChallengeRU
